spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/shop_template
    username: Maria
    password: tmax
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
